<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Photo\Module'                        => __DIR__ . '/Module.php',
    'Photo\Controller\PhotoController' => __DIR__ . '/src/Photo/Controller/PhotoController.php',
    'PhotoTest\Framework\TestCase'        => __DIR__ . '/tests/Photo/Framework/TestCase.php',
    'PhotoTest\SampleTest'                => __DIR__ . '/tests/Photo/SampleTest.php',
);
