<div class="panel panel-primary">
   <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-star"></span> <b>Liste des signalements</b></h3>
   </div>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Signalé par</th>
                <th>Type de signalement</th>
                <th>Profil signalé</th>
                <th>Options</th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
                <td>21/11/2015</td>
                <td>yoda59</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
        
    </table>
</div>