<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-search"></span> <b>Rechercher des membres</b></h3>
   </div>
   <div class="panel-body" style="background-color: #eeeeee">
      <form role="form">
         <div class="row">
            <div class="col-sm-6 col-md-6">
               <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
               </div>
               <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
               </div>
               <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile">
                  <p class="help-block">Example block-level help text here.</p>
               </div>
            </div>
            <div class="col-sm-6 col-md-6">
               <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
               </div>
               <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
               </div>
               <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile">
                  <p class="help-block">Example block-level help text here.</p>
               </div>
            </div>
         </div>
      </form>
   </div>
</div>
