<div class="panel panel-primary">
   <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-eye-open"></span> <b>Vos</b> visites reçues</h3>
   </div>
   <div class="panel-body">
   <?php if(count($profils)): ?>
   
   <div class="row">
   <?php foreach ($profils as $user): ?>
   <div class="col-sm-3 col-md-3 col-xs-6">
       <div class="thumbnail" style="position:relative;">      
          <a href="<?php echo $this->url('user/view',array('id'=>$user->getId())) ?>"><img src="<?php echo $user->getPhoto() ?>" alt="..."></a>           
          <div class="online"><span class="label label-success">En ligne</span></div>
              
              <div class="fix">                 
                  <div class="desc">
                        <p class="desc_content"><small><?php echo $user->getName() ?></small></p>
                  </div>
              </div>
       </div>
   </div>
   <?php endforeach ?>
                        
   </div>
   
   <?php else: ?>
   <div class="alert alert-info" role="alert"><strong>Désolé</strong>, vous n'avez pas eu encore de visite sur votre profil, mais ça ne devrait plus tarder...</div>
   <?php endif ?>
   </div>
</div>
<div class="text-center">
 <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->profils,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'account/visit'
     )
 );
 ?>
 </div>