<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">
			<span class="glyphicon glyphicon-search"></span> <b>Rechercher des
				membres</b>
		</h3>
	</div>
	<div class="panel-body">
		<form role="form" method="get" action="/search">
			<div class="row">
				<div class="col-sm-6 col-md-6">
					<div class="form-group">
						<label for="exampleInputEmail1">Je recherche une femme entre :</label>
						<input id="ex2" type="text" name="age" class="span2" value=""
							data-slider-min="18" data-slider-max="99" data-slider-step="1"
							data-slider-value="[25,40]" /> <b>ans</b>
					</div>
					<div class="form-group">
					    <label for="exampleInputPassword1">A <span id="ex6CurrentSliderValLabel"><span id="ex6SliderVal">50</span> km</span> autour de <?php echo $user->getCityName() ?></label>
					    <div class="input-group">
                          <input id="ex6" type="text" data-slider-min="10" data-slider-max="500" data-slider-step="10" data-slider-value="50">
                          
                        </div>
					  </div>
					<div class="form-group">
						<label for="pseudo">Affiner par pseudo</label> 
						<input type="text" name="pseudo" class="form-control" id="pseudo" placeholder="Saisir un pseudo ou laissez vide">
					</div>
					
					<div class="form-group">
						<label for="exampleInputEmail1">Filtrer les résultats</label>
					<div class="checkbox">
					  <label style="padding-left:20px">
					    <input type="checkbox" value="true" name="online">
					    Uniquement les profils en ligne
					  </label>
					</div>
					<div class="checkbox">
					  <label style="padding-left:20px">
					    <input type="checkbox" value="true" name="photo"> Uniquement les profils avec photo
					  </label>
					</div>
				</div>
				</div>

				<div class="col-sm-6 col-md-6">
					<p class="text-center">
						<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- freemmet_carré -->
						<ins class="adsbygoogle"
						     style="display:inline-block;width:300px;height:250px"
						     data-ad-client="ca-pub-2896902524200753"
						     data-ad-slot="3878534229"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
					</p>
					<input type="submit" class="btn btn-block" value="Rechercher">
				</div>

			</div>
			
		</form>
	</div>
</div>

