<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Chat\Module'                        => __DIR__ . '/Module.php',
    'Chat\Controller\ChatController' => __DIR__ . '/src/Chat/Controller/ChatController.php',
    'ChatTest\Framework\TestCase'        => __DIR__ . '/tests/Chat/Framework/TestCase.php',
    'ChatTest\SampleTest'                => __DIR__ . '/tests/Chat/SampleTest.php',
);
