<div class="col-sm-5 col-md-4 col-lg-3 hidden-sm hidden-xs sidebar">

          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
						

            
            <div class="col-sm-12 col-md-8 col-lg-9 col-xs-12">
            
            <div class="block">
   <div class="title">
      <h3 class="section_header skincolored"><span class="glyphicon glyphicon-flash"></span> <b>Mes </b> parametres</h3>
   </div>
   <div class="content" style="background-color: #eeeeee">
    <h4>Préférence des envois d'emails</h4>
    <div class="row">
    
    <div class="col-md-8">Je souhaite être averti par mail lors d'une visite sur mon profil</div>
    <div class="col-md-4">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
    
    <div class="row">
    
    <div class="col-md-8">Je souhaite être averti par mail lorsque un membre m'envois un flahs</div>
    <div class="col-md-4">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
    
    <div class="row">
    
    <div class="col-md-8">Je souhaite être averti par mail lorsque membre m'envois un message</div>
    <div class="col-md-4">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
    <h4>Sécurité du compte</h4>
    
   </div>
</div>
            
            </div>

