<div class="panel panel-default">
   <div class="panel-heading">
      <button class="btn btn-primary btn-xs pull-right">Enregistrer</button>
      <h3 class="panel-title"><span class="glyphicon glyphicon-cog"></span> <b>Mes </b> paramêtres</h3>
   </div>
   <div class="panel-body">
    <div class="row">
    
    <div class="col-sm-9">Je souhaite être averti par mail lors d'une visite sur mon profil</div>
    <div class="col-sm-3">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
    
    <div class="row">
    
    <div class="col-sm-9">Je souhaite être averti par mail lorsque un membre m'envois un flahs</div>
    <div class="col-sm-3">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
    
    <div class="row">
    
    <div class="col-sm-9">Je souhaite être averti par mail lorsque membre m'envois un message</div>
    <div class="col-sm-3">

    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Oui
    </label>
    <label class="radio-inline">
      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Non
    </label>
    </div>
    </div>
   </div>
</div>

<div class="panel panel-default">
   <div class="panel-heading">
      <button class="btn btn-primary btn-xs pull-right" id="edit_password">Modifier</button>
      <h3 class="panel-title"><span class="glyphicon glyphicon-lock"></span> Modification du mot passe</h3>
   </div>
   <div class="panel-body">
    <form id="editPassword">
          <div class="row">
          <div class="col-md-4">
          <div class="form-group">
            <label  for="exampleInputEmail2">Mot de passe actuel</label>
            <input type="password" name="currentPassword" class="form-control input-sm">
          </div>
          </div>
          <div class="col-md-4">
            <label  for="exampleInputEmail2">Nouveau mot de passe</label>
            <input type="password" name="newPassword" class="form-control input-sm">
        </div>
        
        <div class="col-md-4">
            <label  for="exampleInputEmail2">Répétez le mot de passe</label>
            <input type="password" name="confirmPassword" class="form-control input-sm">
        </div>
        
        </div>
        </form>
   </div>
</div>

<div class="panel panel-default">
   <div class="panel-heading">
      <button class="btn btn-danger btn-xs pull-right">Désactiver mon compte</button>
      <h3 class="panel-title"><span class="glyphicon glyphicon-off"></span> Désactivation du compte</h3>
   </div>
   <div class="panel-body">
      <p>Vous souhaitez suspendre votre compte ? En cliquant sur le bouton ci-dessous votre compte sera désactivé, vous ne serez plus visible pour les autres membres du site.</p>
        <form>
          <div class="row">
          <div class="col-md-7">
          <div class="form-group">
            <label  for="exampleInputEmail2">Je souhaites</label>
            <select class="form-control input-sm">
              <option>Désactiver temporairement mon compte</option>
              <option>Supprimer définitivement mon compte</option>
            </select>
          </div>
          </div>
          <div class="col-md-5">
            <label  for="exampleInputEmail2">Je saisie mon mot de passe</label>
            <input type="password" class="form-control input-sm">
        </div>
        </div>
        </form>
   </div>
</div>