<div class="col-sm-5 col-md-4 col-lg-3 hidden-sm hidden-xs sidebar">
          <div class="panel panel-default" data-spy="affix" data-offset-top="60" data-offset-bottom="200">
          <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-user"></span> <b>Mon </b> profil</h3>
   </div>
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#" class="active"><span class="glyphicon glyphicon-camera"></span> Gérer mes photos <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Mes informations personelles</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-glass"></span> Mes loisirs</a></li>
            <li><a href="#">Mon style de vie</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-search"></span> Mes critères de recherche</a></li>
          </ul>
        </div>
        </div>
						

            
            <div class="col-sm-12 col-md-8 col-lg-9 col-xs-12">
            
           <div class="panel panel-primary">
           
           <div class="panel-heading">
              <a href="#" class="btn btn-primary btn-xs pull-right" id="import"><img src="/img/facebook.gif"> Importer <span class="hidden-xs">depuis facebook</span></a>
              <h3 class="panel-title"><span class="glyphicon glyphicon-camera"></span> <b>Gérer </b> mes photos</h3>
              
           </div>
           <div class="panel-body">
           <form enctype="multipart/form-data">
           <div id="uploadMessages"></div>
           <p>Vous pouvez ajouter jusqu'a 4 photos sur votre profil, elle seront vérifiées au préable par l'équipe de modération avant d'être visible pour les autres membres du site.</p>
           <div class="row">
           <?php foreach($photos as $photo): ?>
           <div class="col-sm-3 col-md-3 col-xs-6">          
           <div class="thumbnail">
              <?php if($photo->getStatus() == 'pending'):?>
              <img src="/photos/pendings/<?php echo $photo->getFilename() ?>">             
              <div class="fix">
                <div class="desc">
                <div class="caption text-center"><h4>Photo <br>en cours<br> de validation</h4></div>
                </div>
              </div>
              <?php else: ?>
              <img src="/photos/<?php echo $photo->getFilename() ?>"> 
              <?php endif; ?>
           </div>
           <p><a href="<?php echo $this->url('photo/delete',array('id'=>$photo->getId())) ?>" class="btn btn-block btn-xs btn-danger">Supprimer</a></p>
           </div>
           <?php endforeach; ?>
           <?php for($i = count($photos); $i < 4; $i++):?>
           <div class="col-sm-3 col-md-3 col-xs-3">
               <div class="thumbnail">
                  <img src="/images/default_man.png" alt="...">
    
               </div>
               <p><input id="add_photo" name="image-file" type="file" data-upload-url="/photo/add"></p>
           </div>
           <?php endfor;?>
           </div>
           </form>
           </div>
           
           </div>       

            
            </div>
            
            <div class="modal fade" id="facebook">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title">Sélectionnez une photo</h5>
      </div>
      <div class="modal-body">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="crop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title">Sélectionnez</h5>
      </div>
      <div class="modal-body">
      <div style="width: 250px" id="photo"></div>
        <div id='controls'>
      <a href='#' id='rotate_left'  title='Rotate left'><i class='glyphicon glyphicon-arrow-left'></i></a>
      <a href='#' id='zoom_out'     title='Zoom out'><i class='glyphicon glyphicon-zoom-out'></i></a>
      <a href='#' id='fit'          title='Fit image'><i class='glyphicon glyphicon-fullscreen'></i></a>
      <a href='#' id='zoom_in'      title='Zoom in'><i class='glyphicon glyphicon-zoom-in'></i></a>
      <a href='#' id='rotate_right' title='Rotate right'><i class='glyphicon glyphicon-repeat'></i></a>
    </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

