<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Logout\Module'                        => __DIR__ . '/Module.php',
    'Logout\Controller\LogoutController' => __DIR__ . '/src/Logout/Controller/LogoutController.php',
    'LogoutTest\Framework\TestCase'        => __DIR__ . '/tests/Logout/Framework/TestCase.php',
    'LogoutTest\SampleTest'                => __DIR__ . '/tests/Logout/SampleTest.php',
);
