<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/application.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.guillotine.css')
                        ->prependStylesheet($this->basePath() . '/css/fileinput.min.css')
                        ->prependStylesheet($this->basePath() . '/css/flexslider.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-slider.css')
                        ->prependStylesheet($this->basePath() . '/css/bootflat.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/application.js')
                                      ->prependFile($this->basePath() . '/js/jquery.slimscroll.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.toaster.js')
                                      ->prependFile($this->basePath() . '/js/moment.js')
                                      ->prependFile($this->basePath() . '/js/fileinput.js')
                                      ->prependFile($this->basePath() . '/js/jquery.guillotine.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.flexslider-min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap-slider.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

        <script src="https://apis.google.com/js/platform.js" async defer>
          {lang: 'fr';}
        </script>
    </head>
    <body>
    <div id="fb-root"></div>

    <header>
    <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button data-target="#bs-example-navbar-collapse-9" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="<?php echo $this->url('account') ?>" class="navbar-brand"><img src="/images/brand.png"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="<?php echo $this->url('search') ?>"><span class="glyphicon glyphicon-search"></span> Membres</a></li>
            <li><a href="<?php echo $this->url('account/favorite') ?>"><span class="glyphicon glyphicon-camera"></span> Photos à valider</a></li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Signalements<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('account/profil') ?>"><span class="glyphicon glyphicon-pencil"></span> Modifier mon profil</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-eye-open"></span> Visualiser mon profil</a></li>
                </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Configuration<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('account/profil') ?>"><span class="glyphicon glyphicon-pencil"></span> Modifier mon profil</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-eye-open"></span> Visualiser mon profil</a></li>
                </ul>
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url('search') ?>"><span class="glyphicon glyphicon-search"></span> Déconnexion</a></li>
          </ul>  
                  
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
</header>
            <div class="container" style="margin-top:70px">
             <?php        
             // In any of your .phtml files:
             $flash = $this->flashMessenger();
             $flash->setMessageOpenFormat('<div>
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                     &times;
                 </button>
                 <ul><li>')
                 ->setMessageSeparatorString('</li><li>')
                 ->setMessageCloseString('</li></ul></div>');
            
             echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
             echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
             echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
             echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
             ?> 
            
            <?php echo $this->content; ?>
            
            
            <hr>
            <footer>
                <div class="row">
                <div class="col-sm-6 hidden-xs">
                <p>&copy; 2009 - <?php echo date('Y') ?> Freemeet.net <span class="hidden-xs"><?php echo $this->translate('All rights reserved.') ?></span></p>
            	</div>
            	<div class="col-sm-6 text-right">
            	<p><a href="">Blog</a> | <a href="">Mentions légales</a></p>
            	</div>
            	</div>
            </footer>
        </div> <!-- /container -->
        <!-- Modal -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
