                        <div class="row">
            <div class="col-sm-3 col-md-4">
                <div class="block">
                    <div class="title">
                        <h3 class="section_header skincolored"><b>Photos</b></h3>                    
                    </div>
                    <div class="content">
                    	<p class="text-center"><img class="img-thumbnail img-responsive" src="http://www.freemeet.net/upload/1288536776.jpg"></p>
                    	<div class="row">
                    	<div class="col-sm-3 col-md-3"><img class="img-rounded img-responsive" src="http://www.freemeet.net/upload/1288536776_xsmall.jpg"></div>
                    	<div class="col-sm-3 col-md-3"><img class="img-rounded img-responsive" src="http://www.freemeet.net/upload/1288536776_xsmall.jpg"></div>
                    	<div class="col-sm-3 col-md-3"><img class="img-rounded img-responsive" src="http://www.freemeet.net/upload/1288536776_xsmall.jpg"></div>
                    	<div class="col-sm-3 col-md-3"><img class="img-rounded img-responsive" src="http://www.freemeet.net/upload/1288536776_xsmall.jpg"></div>
                    	</div>
                	</div>
                </div>
                </div>
                
                <div class="col-sm-6 col-md-8">
                <div class="block">
                	
                    <div class="title">
                        <h3 class="section_header skincolored"><b>En</b> Ligne</h3>                    
                    </div>
                    <div class="content" style="background-color: #eeeeee">
                    </div>
                </div>
                
                </div>
                
                </div>