
<div class="panel panel-success">
<div class="panel-heading" style="background-color: #763568">
<h3 class="panel-title text-uppercase"><strong>Envois d'un message à <?php echo $user->getName() ?></strong></h3>
</div>

<div class="panel-body">

    <?php
    
    $form->setAttribute('action', $this->url('mailbox/add-conversation'));
    $form->prepare();
    ?>
    
    <?php echo $this->form()->openTag($form); ?>

    <div class="form-group">
        <label for="content">Contenu du message :</label>
        <?php echo $this->formRow($form->get('content')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('receiver')); ?>
    </div>
    <div class="text-right">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>

    <?php  echo $this->form()->closeTag(); ?>
</div>

</div>
