
	<div class="col-md-4">
		<div class="panel panel-default">
		    
		   <div class="panel-heading">
		   <h3 class="panel-title text-uppercase"><strong><span class="glyphicon glyphicon-envelope"></span> Mes conversations</strong></h3>
		   </div>
		   
		   <div class="panel-body">
		        <?php if(count($conversations)): ?>		
		        
		        <?php foreach($conversations as $conversation): ?>
		        <?php if($conversation->getLastMessageStatus() == 'unread'):?>
		        <div class="row unread">
		        
		        <?php else: ?>
		        <div class="row">
		        <?php endif ?>
		        
		        	<div class="col-xs-2">
		                <a href="#">
		                  <img alt="50x50" class="img-responsive" src="<?php echo $conversation->getPhoto('xsmall') ?>">
		                </a>
		            </div>
		            <div class="col-xs-10">
		            	<a href="<?php echo $this->url('mailbox/delete',array('id'=>$conversation->getId())) ?>" class="close pull-right" data-toggle="tooltip" data-placement="top" title="Supprimer la conversation"><span aria-hidden="true">&times;</span></a>                
		                <h4 class="media-heading"><a href="<?php echo $this->url('mailbox/view',array('id'=>$conversation->getId())) ?>"><?php echo $conversation->getUsername() ?></a></h4>
		                
		                <p><?php if($this->identity()->user_id == $conversation->getLastUser()) { echo 'Vous : '; }?>
		                   <?php echo $conversation->getLastMessage() ?>
		                </p>
		           </div>
		              
		              
		
		        </div>
		        <hr>
		        <?php endforeach;?>		
		        <?php else: ?>
		        
		        <div class="alert alert-info" style="margin-bottom:0">Vous n'avez pas encore reçu de message.</div>
		        
		        <?php endif ?>
		   </div>
		</div>
	</div>
	
	<div class="col-md-8">
	
		<div class="panel panel-primary">
   			<div class="panel-heading">
		      <h3 class="panel-title"><span class="glyphicon glyphicon-envelope"></span> Messages échangés avec </h3>
		    </div>
   			<div class="panel-body">
   
   				<div data-height="200px" data-scrollbar="true">

				   <ul class="chats">
				      <?php foreach ($messages as $message): ?>   
                                   
					    <?php if($message->getAuthor() == $this->identity()->user_id):?>
					    <li class="right">
					        <span class="date-time" data-time="<?php echo $message->getDate(true) ?>"><?php echo $this->relativeTime($message->getDate()) ?></span>
					        <a class="name" href="javascript:;">Vous</a>
					        <a class="image" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>">
					          <img src="<?php echo $message->getPhoto('small') ?>">
					        </a>
					        <div class="message">
					            <?php echo nl2br($message->getContent()) ?>
					        </div>
					    </li>
					    <?php else : ?>
					    <li class="left">
					        <span class="date-time" data-time="<?php echo $message->getDate(true) ?>"><?php echo $this->relativeTime($message->getDate()) ?></span>
					        <a class="name" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>"><?php echo $this->escapehtml($message->getUsername())?></a>
					        <a class="image" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>">
					          <img src="<?php echo $message->getPhoto('small') ?>">
					        </a>
					        <div class="message">
					            <?php echo nl2br($message->getContent()) ?>
					        </div>
					    </li>
					    <?php endif ?>
					   
					   
					   <?php endforeach; ?>
				   </ul>
   				</div>
   
   			</div>
   
   			<div class="panel-footer">
			   <?php
			    
			    $form->setAttribute('action', $this->url('mailbox/reply'));
			    $form->prepare();
			    ?>
			    
			    <?php echo $this->form()->openTag($form); ?>
			
			    <div class="form-group">
			        <label for="content">Envoyer un message :</label>
			        <?php echo $this->formRow($form->get('content')); ?>
			    </div>
			    <div class="form-group">
			        <?php echo $this->formRow($form->get('conversation')); ?>
			    </div>
			    <div class="text-right">
			        <?php echo $this->formSubmit($form->get('submit')); ?>
			    </div>
			
			    <?php  echo $this->form()->closeTag(); ?>
			   </div>
   
			</div>
	
	</div>
	
	

