<div class="panel panel-primary">
   <div class="panel-heading">
      <h3 class="panel-title"><span class="glyphicon glyphicon-envelope"></span> Messages échangés avec </h3>
   </div>
   <div class="panel-body">
   
   <div data-height="200px" data-scrollbar="true">

   <ul class="chats">
   <?php foreach ($messages as $message): ?>   
                                   
    <?php if($message->getAuthor() == $this->identity()->user_id):?>
    <li class="right">
        <span class="date-time" data-time="<?php echo $message->getDate(true) ?>"><?php echo $this->relativeTime($message->getDate()) ?></span>
        <a class="name" href="javascript:;">Vous</a>
        <a class="image" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>">
          <img src="<?php echo $message->getPhoto('small') ?>">
        </a>
        <div class="message">
            <?php echo nl2br($message->getContent()) ?>
        </div>
    </li>
    <?php else : ?>
    <li class="left">
        <span class="date-time" data-time="<?php echo $message->getDate(true) ?>"><?php echo $this->relativeTime($message->getDate()) ?></span>
        <a class="name" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>"><?php echo $this->escapehtml($message->getUsername())?></a>
        <a class="image" href="<?php echo $this->url('user/view', array('id'=>$message->getAuthor())) ?>">
          <img src="<?php echo $message->getPhoto('small') ?>">
        </a>
        <div class="message">
            <?php echo nl2br($message->getContent()) ?>
        </div>
    </li>
    <?php endif ?>
   
   
   <?php endforeach; ?>
   </ul>
   </div>
   
   </div>
   
   <div class="panel-footer">
   <?php
    
    $form->setAttribute('action', $this->url('mailbox/reply'));
    $form->prepare();
    ?>
    
    <?php echo $this->form()->openTag($form); ?>

    <div class="form-group">
        <label for="content">Envoyer un message :</label>
        <?php echo $this->formRow($form->get('content')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('conversation')); ?>
    </div>
    <div class="text-right">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>

    <?php  echo $this->form()->closeTag(); ?>
   </div>
   
</div>

