<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mailbox\Module'                        => __DIR__ . '/Module.php',
    'Mailbox\Controller\MailboxController' => __DIR__ . '/src/Mailbox/Controller/MailboxController.php',
    'MailboxTest\Framework\TestCase'        => __DIR__ . '/tests/Mailbox/Framework/TestCase.php',
    'MailboxTest\SampleTest'                => __DIR__ . '/tests/Mailbox/SampleTest.php',
);
