<section id="slider_wrapper" class="slider_wrapper full_page_photo">
     <div id="main_flexslider" class="flexslider">
          <ul class="slides">
               <li class="item" style="background-image: url(/images/1.jpg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1>un site de rencontres <strong>gratuit</strong><br>
                                   pour des <strong>rencontres sérieuses</strong></h1>
                              <p class="lead skincolored"><strong>Freemeet</strong> est un site de rencontre gratuit et <strong>sans abonnement</strong> vous pouvez utiliser toutes les fonctionnalitées du site sans aucune limitation pour trouver les célibataires et peut être trouver l'amour.</p>
                              <span class="round_badge"><strong><i class="fa fa-twitter"></i></strong><strong>Je m'inscris en 1 clic</strong></span> </div>
                    </div>
               </li>
               <li class="item" style="background-image: url(/images/2.jpg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1>Des outils <strong>innovants</strong><br>
                                   pour trouver <strong>l'amour</strong></h1>
                              <p class="lead skincolored">Restart was built with heavy use of {less} technology, making the life of the web developer easier!</p>
                         </div>
                    </div>
               </li>
               <li class="item" style="background-image: url(/images/3.jpg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1 class="skincolored">Découvrez <strong>le Mag</strong></h1>
                              <p class="lead">Si vous avez besoin de <a href="services.html"><strong>conseils en séduction</strong> </a> freemeet met à votre disposition<br>
                                   de nombreux articles pour vous aider dans votre quête de l'amour !</p>
                         </div>
                    </div>
               </li>
          </ul>
     </div>
</section>

<div class="container">
          <section class="call_to_action">
               <h3>Inscrivez-vous c'est gratuit !</h3>
               <h4>et découvrez les célibataires qui vous correspondent</h4>
        
       <img width="60px" height="60px" class="img-thumbnail" src="http://freemeet.net/upload/1375216162_xsmall.jpg">&nbsp;<img  class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1374006431_xsmall.jpg">&nbsp;<img class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1354444465_xsmall.jpg">&nbsp;<img class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1341567663_xsmall.jpg">&nbsp;<img class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1372247465_xsmall.jpg">&nbsp;<img class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1358777151_xsmall.jpg">&nbsp;<img class="img-thumbnail" width="60px" height="60px" src="http://freemeet.net/upload/1365679330_xsmall.jpg">
          </section>
     </div>
